// ======================================================================
// \title  C.hpp
// \author Generated by fpp tools
// \brief  hpp file for CppDoc test
// ======================================================================

#ifndef N_C_HPP
#define N_C_HPP

namespace N {

  class C {

    public:

      // ----------------------------------------------------------------------
      // Nested class
      // ----------------------------------------------------------------------

      class N {

        public:

          //! This is line 1.
          //!
          //! This is line 3.
          N();

          //! This is line 1.
          //! This is line 2.
          ~N();

          //! This is line 1.
          //! This is line 2.
          void f(
              const double x, //!< This is parameter x line 1.
                              //!<
                              //!< This is parameter x line 3.
              const int y //!< This is parameter y line 1.
                          //!< This is parameter y line 2.
          );

      };

      // ----------------------------------------------------------------------
      // Consructors and destructors
      // ----------------------------------------------------------------------

      //! This is line 1.
      //! This is line 2.
      C(
          const double x, //!< This is parameter x
          const int y //!< This is parameter y
      );

      //! This is line 1.
      //! This is line 2.
      ~C();

    public:

      // ----------------------------------------------------------------------
      // Public member functions
      // ----------------------------------------------------------------------

      //! This is line 1.
      //! This is line 2.
      void f(
          const double x = 0.0, //!< This is parameter x
          const int y = 0 //!< This is parameter y
      );

      //! This is line 1.
      //! This is line 2.
      virtual void g() const = 0;

    private:

      // ----------------------------------------------------------------------
      // Private member variables
      // ----------------------------------------------------------------------

      //! Member variable x
      double x;

      //! Member variable y
      int y;

  };

}

namespace M {

  class M {

    public:

      //! This is line 1.
      //!
      //! This is line 3.
      M();

      //! This is line 1.
      //! This is line 2.
      virtual ~M();

  };

}

#endif
