// ======================================================================
// \title  Other.cpp
// \author Generated by fpp tools
// \brief  cpp file for CppDoc test
// ======================================================================

#include "C.hpp"

namespace N {

  void C::N ::
    f(
        const double x,
        const int y
    )
  {

  }

}

namespace M {

  M ::
    M()
  {
    // line1
    // line2
  }

  M ::
    ~M()
  {
    // Body line 1
    // Body line 2
  }

}
