"""A C++ document representing an .hpp file and one or more .cpp files"""

from __future__ import annotations
from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Optional, List

from fprime_python_model.utils.line_utils import Lines, Line

# Note that the Scala version contains two fields in the Lines
# class: output and cpp_file_name_base_opt, which do not occur in 
# fprime_python_model.utils.line_utils.Lines.

@dataclass
class CppDoc:
    """A C++ document representing an .hpp file and one or more .cpp files"""
    description: str
    hpp_file: HppFile
    cpp_file_name: str
    members: List[Member]
    tool_name_opt: Optional[str] = None
    file_banner_opt: Optional[FileBanner] = None

    def get_file_banner(self) -> FileBanner:
        """Get the file banner"""
        return self.file_banner_opt if self.file_banner_opt else DefaultFileBanner(self.tool_name_opt)


@dataclass
class HppFile:
    """An hpp file"""
    name: str
    include_guard: str


# Top-level document members
class Member(ABC):
    """Base class for document members"""
    pass


@dataclass
class MemberClass(Member):
    """A class member"""
    c: Class


@dataclass
class MemberLines(Member):
    """A lines member"""
    lines: Lines


@dataclass
class MemberFunction(Member):
    """A function member"""
    function: Function


@dataclass
class MemberNamespace(Member):
    """A namespace member"""
    namespace: 'Namespace'


class FileBanner(ABC):
    """A generic file banner"""

    def get_title(self, file_name: str) -> str:
        """Get the title"""
        raise NotImplementedError

    def get_author(self, file_name: str) -> str:
        """Get the author"""
        raise NotImplementedError

    def get_description(self, file_name: str, generic_description: str) -> str:
        """Get description"""
        raise NotImplementedError


@dataclass
class DefaultFileBanner(FileBanner):
    """The default file banner"""
    tool_name_opt: Optional[str] = None

    def get_title(self, file_name: str) -> str:
        return file_name

    def get_author(self, file_name: str) -> str:
        return f"Generated by {self.tool_name_opt if self.tool_name_opt else 'fpp tools'}"

    def get_description(self, file_name: str, generic_description: str) -> str:
        return generic_description


@dataclass
class Class:
    """A C++ class"""
    comment: Optional[str]
    name: str
    superclass_decls: Optional[str]
    members: List[ClassMember]
    qualifier: FinalQualifier = field(default_factory=lambda: FinalQualifier.NON_FINAL)
    
    
# Forward declarations for recursive types
class ClassMember(ABC):
    """Base class for class members"""
    pass


@dataclass
class ClassMemberClass(ClassMember):
    """A nested class member"""
    c: 'Class'


@dataclass
class ClassMemberConstructor(ClassMember):
    """A constructor member"""
    constructor: Constructor


@dataclass
class ClassMemberDestructor(ClassMember):
    """A destructor member"""
    destructor: Destructor


@dataclass
class ClassMemberLines(ClassMember):
    """A lines member"""
    lines: Lines


@dataclass
class ClassMemberFunction(ClassMember):
    """A function member"""
    function: Function
    

class FinalQualifier(Enum):
    """Class final qualifier"""
    FINAL = auto()
    NON_FINAL = auto()
    

@dataclass
class Constructor:
    """A C++ constructor"""
    comment: Optional[str]
    params: List[FunctionParam]
    initializers: List[str]
    body: List[Line]
    explicit_qualifier: ExplicitQualifier = field(default_factory=lambda: ExplicitQualifier.NOT_EXPLICIT)
    cpp_file_name_base_opt: Optional[str] = None


class ExplicitQualifier(Enum):
    """Constructor explicit qualifier"""
    NOT_EXPLICIT = auto()
    EXPLICIT = auto()                


@dataclass
class Destructor:
    """A C++ destructor"""
    comment: Optional[str]
    body: List[Line]
    virtual_qualifier: VirtualQualifier = field(default_factory=lambda: VirtualQualifier.NON_VIRTUAL)
    cpp_file_name_base_opt: Optional[str] = None


class VirtualQualifier(Enum):
    """Destructor virtual qualifier"""
    NON_VIRTUAL = auto()
    VIRTUAL = auto()
    
    
@dataclass
class Function:
    """A C++ function, either standalone or inside a class"""
    comment: Optional[str]
    name: str
    params: List[FunctionParam]
    ret_type: Type
    body: List[Line]
    sv_qualifier: SVQualifier = field(default_factory=lambda: SVQualifier.NON_SV)
    const_qualifier: ConstQualifier = field(default_factory=lambda: ConstQualifier.NON_CONST)
    cpp_file_name_base_opt: Optional[str] = None


@dataclass
class FunctionParam:
    """A function parameter"""
    t: Type
    name: str
    comment: Optional[str] = None
    default: Optional[str] = None
    

class SVQualifier(Enum):
    """Function static/virtual qualifier"""
    FINAL = auto()
    NON_SV = auto()
    OVERRIDE = auto()
    PURE_VIRTUAL = auto()
    STATIC = auto()
    VIRTUAL = auto()


class ConstQualifier(Enum):
    """Function const qualifier"""
    CONST = auto()
    NON_CONST = auto() 
       

@dataclass
class Namespace:
    """A C++ namespace"""
    name: str
    members: List[Member]


@dataclass
class Type:
    """A C++ type. The .cpp spelling of the type can be different from the .hpp type.
    E.g., the .cpp version may need more qualifiers."""
    hpp_type: str
    cpp_type: Optional[str] = None

    def get_cpp_type(self) -> str:
        """Get the C++ type, defaulting to hpp_type if cpp_type is not specified"""
        return self.cpp_type if self.cpp_type  else self.hpp_type


if __name__ == "__main__":
    print("basic check")
    
    