"""Test utilities for C++ code generation tests"""

import subprocess
import tempfile
import os
import unittest
from pathlib import Path
from typing import List, Dict
from fprime_python_model.utils.line_utils import Line

# Path to gold standard files
GOLD_STANDARD_DIR = Path(__file__).parent / "gold_standard"


def assert_matches_gold_standard(test_case: unittest.TestCase, generated: List[Line], filename: str) -> None:
    """
    Compare generated output against gold standard file.

    Args:
        test_case: The unittest.TestCase instance for assertions
        generated: List of Line objects generated by Python code
        filename: Name of the gold standard file (e.g., "C.hpp", "C.cpp", "Other.cpp")
    """
    import difflib

    gold_standard_path = GOLD_STANDARD_DIR / filename

    # Read gold standard file
    with open(gold_standard_path, 'r') as f:
        gold_standard = f.read()

    # Convert generated lines to string
    generated_str = "\n".join(str(line) for line in generated)

    # Add trailing newline to match file format
    if not generated_str.endswith("\n"):
        generated_str += "\n"

    # Compare
    if generated_str != gold_standard:
        # Generate unified diff for better readability
        gold_lines = gold_standard.splitlines(keepends=True)
        gen_lines = generated_str.splitlines(keepends=True)
        diff = difflib.unified_diff(
            gold_lines, gen_lines,
            fromfile=f"gold_standard/{filename}",
            tofile=f"generated/{filename}",
            lineterm=''
        )
        diff_output = '\n'.join(diff)

        test_case.fail(
            f"Generated {filename} does not match gold standard:\n\n{diff_output}"
        )


def compile_and_assert(test_case: unittest.TestCase, files: Dict[str, List[Line]]) -> None:
    """
    Compile generated C++ files using gcc and assert success.

    Args:
        test_case: The unittest.TestCase instance for assertions
        files: Dictionary mapping filenames to lists of Line objects
               Example: {"C.hpp": hpp_lines, "C.cpp": cpp_lines, "Other.cpp": other_lines}

    Raises:
        SkipTest: If gcc is not available
    """
    try:
        result = compile_cpp_files(files)

        # Print output for debugging
        if result.stdout:
            print("\n=== GCC stdout ===")
            print(result.stdout)
        if result.stderr:
            print("\n=== GCC stderr ===")
            print(result.stderr)

        # Check compilation succeeded
        test_case.assertEqual(result.returncode, 0, f"GCC compilation failed:\n{result.stderr}")

        print("\n=== GCC Compilation Successful ===")

    except FileNotFoundError:
        test_case.skipTest("gcc not found - skipping compilation test")


def compile_cpp_files(files: Dict[str, List[Line]]) -> subprocess.CompletedProcess:
    """
    Compile generated C++ files using gcc.

    Args:
        files: Dictionary mapping filenames to lists of Line objects
               Example: {"C.hpp": hpp_lines, "C.cpp": cpp_lines, "Other.cpp": other_lines}

    Returns:
        subprocess.CompletedProcess with compilation results

    Raises:
        FileNotFoundError: If gcc is not available
    """
    with tempfile.TemporaryDirectory() as tmpdir:
        # Write all files to temporary directory
        for filename, lines in files.items():
            filepath = os.path.join(tmpdir, filename)
            with open(filepath, 'w') as f:
                f.write("\n".join(str(line) for line in lines))

        # Get list of .cpp files to compile
        cpp_files = [name for name in files.keys() if name.endswith('.cpp')]

        # Compile with gcc
        result = subprocess.run(
            ["gcc", "-c"] + cpp_files,
            cwd=tmpdir,
            capture_output=True,
            text=True,
            timeout=10
        )

        return result
